language: generic
deploy:
  provider: s3
  access_key_id: AKIAJV5AHNZM7V4VPRZA
  secret_access_key: 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
  bucket: web-p
  on:
    repo: karamba5/Hello-World
  acl: public_read
